env: 'local' #local, dev, prod

limitC: 10
maxItemsC: 100

http_server:
  port: "8081"
  timeout: 4s
  idle_timeout: 60s

db:
  driver: 'postgres'
  host: 'postgres'
  port: 5432
  username: 'orders_user'
  password: 'orders_password'
  dbname: 'orders_db'

kafka:
  brokers: 
    - 'kafka:9092'
  topic: 'order_topic'
  dlq_topic: 'order_topic_dlq'
  group_id: 'order-service'
  retry_delay: 15s
